### PR TITLE
Synchronised the internal and ui max skylander count

### PR DESCRIPTION
**Pull request by mandar1jn**
- Created the MAX_SKYLANDERS macro that holds the maximum amount of Skylanders possible
- Increased MAX_SKYLANDERS to 16 (the max limit a portal can handle)

### CODE REVIEW

**Comment by mandar1jn** [comment]
DON'T MERGE!!!

**Comment by mandar1jn** [comment]
It seems like I have broken the status or smth with the last commit

**Comment by mandar1jn** [comment]
Nevermind. Feel free to merge. Please test it first just to make sure

**Comment by deReeperJosh** [comment]
> Nevermind. Feel free to merge. Please test it first just to make sure

Awesome, thanks for this, testing now with the r+b fix as well locally :)

**Comment by deReeperJosh** [comment]
The UI window doesn't look great with 16 Skylanders, needs to be full screen in order for me to see the Clear/Create/Load buttons and the Skylander's name on my Macbook. I'll look at trying to make it scrollable potentially.

**Comment by deReeperJosh** [comment]
Closing this off with the latest changes made in my local branch

**Pull request closed without merging**
